-- Project PenPal initial database schema
-- Run this entire file once in the Supabase SQL Editor.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  birth_year integer,
  country text,
  region text,
  about_me text,
  languages text[] not null default '{}',
  friendship_goals text[] not null default '{}',
  communication_style text,
  correspondence_frequency text,
  accepting_new_penpals boolean not null default true,
  max_penpals integer not null default 3,
  onboarding_complete boolean not null default false,
  discoverable boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_display_name_length check (display_name is null or char_length(display_name) between 2 and 40),
  constraint profiles_birth_year_range check (birth_year is null or birth_year between 1900 and 2100),
  constraint profiles_about_length check (about_me is null or char_length(about_me) <= 2000),
  constraint profiles_communication_style check (
    communication_style is null or communication_style in ('short', 'medium', 'long', 'any')
  ),
  constraint profiles_correspondence_frequency check (
    correspondence_frequency is null or correspondence_frequency in ('several_week', 'weekly', 'biweekly', 'monthly', 'flexible')
  ),
  constraint profiles_max_penpals check (max_penpals between 1 and 10)
);

create table if not exists public.interests (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique
);

create table if not exists public.profile_interests (
  profile_id uuid not null references public.profiles(id) on delete cascade,
  interest_id bigint not null references public.interests(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (profile_id, interest_id)
);

alter table public.profiles enable row level security;
alter table public.interests enable row level security;
alter table public.profile_interests enable row level security;

-- Supabase projects created with automatic Data API exposure disabled require
-- explicit table privileges in addition to RLS policies.
grant usage on schema public to authenticated;
grant select, insert, update on table public.profiles to authenticated;
grant select on table public.interests to authenticated;
grant select, insert, delete on table public.profile_interests to authenticated;

grant select, insert, update, delete on table public.profiles to service_role;
grant select, insert, update, delete on table public.interests to service_role;
grant select, insert, update, delete on table public.profile_interests to service_role;

-- Profiles: authenticated users can see their own profile and completed profiles
-- that have chosen to appear in discovery.
drop policy if exists "Profiles are visible to their owner and discovery" on public.profiles;
create policy "Profiles are visible to their owner and discovery"
on public.profiles for select
to authenticated
using (
  id = auth.uid()
  or (discoverable = true and onboarding_complete = true)
);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

-- Interest choices themselves are non-sensitive reference data.
drop policy if exists "Authenticated users can view interests" on public.interests;
create policy "Authenticated users can view interests"
on public.interests for select
to authenticated
using (true);

-- A user's interests are visible when their profile is visible, or to themselves.
drop policy if exists "Profile interests follow profile visibility" on public.profile_interests;
create policy "Profile interests follow profile visibility"
on public.profile_interests for select
to authenticated
using (
  profile_id = auth.uid()
  or exists (
    select 1
    from public.profiles p
    where p.id = profile_id
      and p.discoverable = true
      and p.onboarding_complete = true
  )
);

drop policy if exists "Users can add their own interests" on public.profile_interests;
create policy "Users can add their own interests"
on public.profile_interests for insert
to authenticated
with check (profile_id = auth.uid());

drop policy if exists "Users can remove their own interests" on public.profile_interests;
create policy "Users can remove their own interests"
on public.profile_interests for delete
to authenticated
using (profile_id = auth.uid());

-- Automatically create an empty profile record whenever a new auth user is created.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id)
  values (new.id)
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute procedure public.set_updated_at();

-- Seed the initial interest catalog. Re-running this section is safe.
insert into public.interests (slug, name) values
  ('art', 'Art'),
  ('board-games', 'Board games'),
  ('books', 'Books & reading'),
  ('cooking', 'Cooking'),
  ('crafts', 'Crafts & DIY'),
  ('culture', 'Culture'),
  ('dogs', 'Dogs'),
  ('cats', 'Cats'),
  ('film-tv', 'Film & television'),
  ('fitness', 'Fitness'),
  ('food', 'Food'),
  ('gardening', 'Gardening'),
  ('gaming', 'Gaming'),
  ('history', 'History'),
  ('hiking', 'Hiking & outdoors'),
  ('languages', 'Languages'),
  ('lgbtq', 'LGBTQ+ community'),
  ('music', 'Music'),
  ('nature', 'Nature'),
  ('photography', 'Photography'),
  ('politics', 'Politics & current events'),
  ('science', 'Science'),
  ('science-fiction', 'Science fiction'),
  ('spirituality', 'Spirituality'),
  ('sports', 'Sports'),
  ('technology', 'Technology'),
  ('theater', 'Theater'),
  ('theme-parks', 'Theme parks'),
  ('travel', 'Travel'),
  ('volunteering', 'Volunteering'),
  ('writing', 'Writing')
on conflict (slug) do update set name = excluded.name;
